peso = float(input("Ingrese su peso (en kg): "))
estatura = float(input("Ingrese su estatura (en metros): "))
imc = (peso) / (estatura**2)
imc_round = round(imc,2)
print(f"Tu índice de masa corporal es de {imc_round}")